# Generated by Django 3.1.1 on 2020-09-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flea_app', '0004_post_image_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.TextField(null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='external_id',
            field=models.PositiveIntegerField(null=True, verbose_name='ID в Барахолке'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_location',
            field=models.TextField(null=True, verbose_name='Фото'),
        ),
    ]
