# Generated by Django 3.1.1 on 2020-09-16 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flea_app', '0005_auto_20200914_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_location',
            new_name='image_file_id',
        ),
    ]
